apiVersion: cert-manager.io/v1alpha2
kind: ClusterIssuer
metada: 
  name: letsencrypt
  namespace: cert-manager
spec:
  acme:
    server: http://acme-v02.api.letsencrypt.org/directory
    email: gui@schafer.net
    privateKeySecretRef:
      name: letsencrypt-tls
    solvers:
    - http01:
        ingress:
          class: nginx